/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ThreeExamplesSplatRouteImport } from './routes/three-examples/$'
import { Route as ApiResultsSplatRouteImport } from './routes/api/results/$'
import { Route as ScenesNameIndexRouteImport } from './routes/scenes/$name/index'
import { Route as ScenesNameLiveRendererRouteImport } from './routes/scenes/$name/live/$renderer'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreeExamplesSplatRoute = ThreeExamplesSplatRouteImport.update({
  id: '/three-examples/$',
  path: '/three-examples/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResultsSplatRoute = ApiResultsSplatRouteImport.update({
  id: '/api/results/$',
  path: '/api/results/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenesNameIndexRoute = ScenesNameIndexRouteImport.update({
  id: '/scenes/$name/',
  path: '/scenes/$name/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenesNameLiveRendererRoute = ScenesNameLiveRendererRouteImport.update({
  id: '/scenes/$name/live/$renderer',
  path: '/scenes/$name/live/$renderer',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/three-examples/$': typeof ThreeExamplesSplatRoute
  '/api/results/$': typeof ApiResultsSplatRoute
  '/scenes/$name/': typeof ScenesNameIndexRoute
  '/scenes/$name/live/$renderer': typeof ScenesNameLiveRendererRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/three-examples/$': typeof ThreeExamplesSplatRoute
  '/api/results/$': typeof ApiResultsSplatRoute
  '/scenes/$name': typeof ScenesNameIndexRoute
  '/scenes/$name/live/$renderer': typeof ScenesNameLiveRendererRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/three-examples/$': typeof ThreeExamplesSplatRoute
  '/api/results/$': typeof ApiResultsSplatRoute
  '/scenes/$name/': typeof ScenesNameIndexRoute
  '/scenes/$name/live/$renderer': typeof ScenesNameLiveRendererRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/three-examples/$'
    | '/api/results/$'
    | '/scenes/$name/'
    | '/scenes/$name/live/$renderer'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/three-examples/$'
    | '/api/results/$'
    | '/scenes/$name'
    | '/scenes/$name/live/$renderer'
  id:
    | '__root__'
    | '/'
    | '/three-examples/$'
    | '/api/results/$'
    | '/scenes/$name/'
    | '/scenes/$name/live/$renderer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ThreeExamplesSplatRoute: typeof ThreeExamplesSplatRoute
  ApiResultsSplatRoute: typeof ApiResultsSplatRoute
  ScenesNameIndexRoute: typeof ScenesNameIndexRoute
  ScenesNameLiveRendererRoute: typeof ScenesNameLiveRendererRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/three-examples/$': {
      id: '/three-examples/$'
      path: '/three-examples/$'
      fullPath: '/three-examples/$'
      preLoaderRoute: typeof ThreeExamplesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/results/$': {
      id: '/api/results/$'
      path: '/api/results/$'
      fullPath: '/api/results/$'
      preLoaderRoute: typeof ApiResultsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenes/$name/': {
      id: '/scenes/$name/'
      path: '/scenes/$name'
      fullPath: '/scenes/$name/'
      preLoaderRoute: typeof ScenesNameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenes/$name/live/$renderer': {
      id: '/scenes/$name/live/$renderer'
      path: '/scenes/$name/live/$renderer'
      fullPath: '/scenes/$name/live/$renderer'
      preLoaderRoute: typeof ScenesNameLiveRendererRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ThreeExamplesSplatRoute: ThreeExamplesSplatRoute,
  ApiResultsSplatRoute: ApiResultsSplatRoute,
  ScenesNameIndexRoute: ScenesNameIndexRoute,
  ScenesNameLiveRendererRoute: ScenesNameLiveRendererRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
