name: Deploy three-ss-fidelity to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy three-ss-fidelity to Cloud Run
    uses: ./.github/workflows/deploy-service.yml
    with:
      service_name: three-ss-fidelity
      dockerfile: Dockerfile
      context: .
    secrets:
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
